### ISSUE TITLE
Small bug (isNotNew)

### ISSUE THREAD

**Issue by Enkey** [php-kitchen/yii2-domain#1]
Small bug here
https://github.com/dekeysoft/yii2-domain/blob/master/src/db/Record.php#L63

**Comment by prowwid** [comment]
Hello @Enkey,

I deeply sorry I haven't noticed your issue when you posted it. 
I had a lot of PRs in April so notification for this issue just got lost in tons of other notifications.

The issue is already fixed. 
Thanks for the participation!

With best regards,
Dmitry Kolodko
